#!/usr/bin/env python3
import sys
from lncli import cmds

if not sys.argv[1:]:
    sys.exit()

file = sys.stdout
# file = sys.stderr
cmd = sys.argv[1]
file.write(cmds().get(cmd, ''))
sys.exit(file == sys.stderr)
